### ISSUE TITLE
🐞 错误报告 登录问题

### ISSUE THREAD

**Issue by InfiniteOpen** [JimmyLv/BibiGPT-v1#168]
# 错误报告 🐞

本地部署的也需要登录吗，点击登录之后显示:
![Snipaste_2023-12-18_14-44-25](https://github.com/JimmyLv/BibiGPT-v1/assets/114172807/437c3540-eb6f-4b55-88fa-f87a28a3255b)

## 错误描述 🤔

无法登录，有的视频在在线的网站上可以获取字幕但是本地却不行，日志显示无法获取字幕,并且还会消耗次数
![Snipaste_2023-12-18_14-45-39](https://github.com/JimmyLv/BibiGPT-v1/assets/114172807/d827b98f-01ee-4ee4-b112-3c17c590b679)

## 附加信息 📝

Docker 部署，页面上显示的确实老的版本，这个是正常的吗？
![Snipaste_2023-12-18_14-46-09](https://github.com/JimmyLv/BibiGPT-v1/assets/114172807/fe898840-c471-447f-bdc3-ac31a361dc32)

感谢您的反馈！🙏

**Comment by JimmyLv** [comment]
是的哈，这里是v1版本
