### ISSUE TITLE
🐞 错误报告 ：无限登录循环，想用Notion登录后，好保存到Notion

### ISSUE THREAD

**Issue by ottopan** [JimmyLv/BibiGPT-v1#169]
# 错误报告 🐞

![image](https://github.com/JimmyLv/BibiGPT-v1/assets/18224971/5f98c69d-f52d-4830-87e8-0fe9a37d0c2f)

## 错误描述 🤔

每次点击“保存到Notion”，就会弹窗登录
还有一点不明白，为啥google登录了就不能使用Notion保存服务，没什么必然联系吧？

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by JimmyLv** [comment]
感谢反馈！这一点在跟进中啦 😁

**Comment by JimmyLv** [comment]
现在支持自行设置  notion token 啦 https://bibigpt.co/blog/posts/bibigpt-ai-summary-sync-guide-10-platforms#notion%E5%90%8C%E6%AD%A5
