### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by ariesbetty** [JimmyLv/BibiGPT-v1#170]
# 错误报告 🐞

目前网站打不开了

## 错误描述 🤔

bibigpt.co打不开，备用网站也打不开，早上的时候还能打开，但是发现总结的记录打不开，然后网站就彻底打不开了。而且最近频繁出现无法总结的情况，明明视频很长，却总提示视频太短。这个问题我之前也通过邮箱反馈过，是个peach开头的163邮箱。
因为我是个程序小白，只是偶然知道这个bibigpt，发现非常好用，直接买了好多时长，现在根本离不开，所以最近的频发问题让我特别难受，求帮助QaQ
## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by JimmyLv** [comment]
特别感谢您的反馈呀！刚好那会儿服务器故障，之后您可以直接链接 hi@bibigpt.co 这个邮箱哦
