### ISSUE TITLE
🐞 错误报告 本地上传音频文件，尝试多次仍然提示无法转录音频

### ISSUE THREAD

**Issue by misparking** [JimmyLv/BibiGPT-v1#175]
# 错误报告 🐞

提示 fail to transcribe  the audio fail to fetch 
![Uploading WechatIMG410.jpg…](https://s1.imagehub.cc/images/2024/02/18/788578cbad8a1e13385a9411f0ccb82f.png)

## 错误描述 🤔

上传本地音频文件，分别多次尝试上传时长7分钟和时长2分钟的m4a音频文件，显示上传成功，但最终转录时会失败。

**Comment by JimmyLv** [comment]
fixed
