### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by jchgjchg** [JimmyLv/BibiGPT-v1#178]
failed to solve: process "/bin/sh -c npm ci && npm run build" did not complete successfully: exit code: 1

运行 docker compose up -d  没顺利结束

因为前面运行时出现过找不到 .env 的情况， 所以我把yaml 里的.env 指向了 .example.env, 然后配置的这个文件

**Comment by JimmyLv** [comment]
最好还是直接修改为 .env，约定的
